import type { DataTableLabels } from "../types";

type ResolvedDataTableLabels = Required<DataTableLabels>;

export const DATA_TABLE_DEFAULT_LABELS: ResolvedDataTableLabels = {
  searchPlaceholder: "Search rows...",
  searchTable: "Search table",
  clearSearch: "Clear search",
  noRowsTitle: "No rows yet",
  noRowsDescription: "Create a record or refresh this view once data exists.",
  noMatchingRowsTitle: "No matching rows",
  noMatchingRowsDescription: "Try a different search term or clear filters.",
  tableOptions: "Show table options",
  columns: "Columns",
  filters: "Filters",
  clearFilters: "Clear filters",
  filterFrom: "From",
  filterTo: "To",
  filterTrue: "Yes",
  filterFalse: "No",
  selectedRows: (count) =>
    `${count} record${count === 1 ? "" : "s"} selected`,
  showHiddenRows: (label) => `Show ${label}`,
  recordsPerPage: "Records per page",
  totalRecords: (count) => `Total records: ${count}`,
  pageStatus: (pageIndex, pageCount) => `Page ${pageIndex + 1} of ${pageCount}`,
  pageStatusUnknown: (pageIndex) => `Page ${pageIndex + 1}`,
  pagination: "Pagination",
  morePages: "More pages",
  firstPage: "First page",
  previousPage: "Previous page",
  nextPage: "Next page",
  lastPage: "Last page",
  selectAllVisibleRows: "Select all visible rows",
  selectAllFilteredRows: "Select all filtered rows",
  selectRow: "Select row",
  selectCardRow: (rowId) => `Select row ${rowId}`,
  switchToTableView: "Switch to table view",
  switchToCardView: "Switch to card view",
  tableView: "Table view",
  cardView: "Card view",
  allFilterOptions: "All",
  actions: "Actions",
  rowActions: "Row actions",
  editRow: "Edit row",
  saveEdit: "Save",
  cancelEdit: "Cancel editing",
  expandRow: "Expand row",
  collapseRow: "Collapse row",
  expandRowDetails: "Expand row details",
  collapseRowDetails: "Collapse row details",
  exportCsv: "Export CSV",
  density: "Density",
  compactDensity: "Compact",
  comfortableDensity: "Comfortable",
  spaciousDensity: "Spacious",
  pinLeft: "Pin left",
  pinRight: "Pin right",
  unpin: "Unpin",
  pinRowToTop: "Pin row to top",
  pinRowToBottom: "Pin row to bottom",
  unpinRow: "Unpin row",
  resizeColumn: (columnLabel) => `Resize ${columnLabel}`,
  grouping: "Grouping",
  groupBy: (columnLabel) => `Group by ${columnLabel}`,
  ungroup: (columnLabel) => `Ungroup ${columnLabel}`,
  removeGrouping: (columnLabel) => `Remove ${columnLabel} grouping`,
  moveGroupingEarlier: (columnLabel) => `Move ${columnLabel} grouping earlier`,
  moveGroupingLater: (columnLabel) => `Move ${columnLabel} grouping later`,
  facetSearch: (columnLabel) => `Search ${columnLabel} options`,
  searchColumns: "Search columns",
  showAllColumns: "Show all columns",
  hideAllColumns: "Hide all columns",
  moveColumnEarlier: (columnLabel) => `Move ${columnLabel} earlier`,
  moveColumnLater: (columnLabel) => `Move ${columnLabel} later`,
  resetColumnLayout: "Reset column layout",
  savedViews: "Saved views",
  createSavedView: "Create saved view",
  savedViewName: "View name",
  applySavedView: (name) => `Apply saved view ${name}`,
  renameSavedView: (name) => `Rename saved view ${name}`,
  deleteSavedView: (name) => `Delete saved view ${name}`,
  saveSavedView: "Save view",
};

export function resolveDataTableLabels(
  labels?: Partial<DataTableLabels>,
): ResolvedDataTableLabels {
  return {
    ...DATA_TABLE_DEFAULT_LABELS,
    ...labels,
  } as ResolvedDataTableLabels;
}
