import type * as React from "react";
import type { ExpandedState, OnChangeFn, Row } from "@tanstack/react-table";
import type { DataTableLabels, DataTableProps } from "../types";
import type { DataTableUiClassNames, DataTableUiKit } from "../ui-kit";

export type DataTableCardPanelProps<TData> = {
  cardClassName: string | undefined;
  cardGridClassName: string | undefined;
  cardSizing: DataTableProps<TData>["cardSizing"];
  cardRenderer: NonNullable<DataTableProps<TData>["cardRenderer"]>;
  containerWidth: number;
  currentRowSelection: Record<string, boolean>;
  currentDetailExpanded: ExpandedState;
  DataTableCardView: React.ElementType;
  DataTableEmptyState: React.ElementType;
  dragAndDrop: DataTableProps<TData>["dragAndDrop"];
  editableRows: DataTableProps<TData>["editableRows"];
  editingRowId: string | null;
  emptyNode: React.ReactNode;
  enableRowSelection: boolean;
  flexGrow: boolean;
  getRowClassName: DataTableProps<TData>["getRowClassName"];
  hasCardTitle: boolean;
  infiniteScroll: DataTableProps<TData>["infiniteScroll"];
  localSearchValue: string;
  onRowClick: DataTableProps<TData>["onRowClick"];
  renderedRows: Array<Row<TData>>;
  detailPanel: DataTableProps<TData>["detailPanel"];
  resolvedLabels: DataTableLabels;
  resolvedLoadingRowCount: number;
  rowActions: DataTableProps<TData>["rowActions"];
  ScrollArea: DataTableUiKit["ScrollArea"];
  scrollbarVisibility: DataTableProps<TData>["scrollbarVisibility"];
  sentinelRef: React.RefObject<HTMLDivElement | null>;
  setCurrentRowSelection: (rowSelection: Record<string, boolean>) => void;
  setCurrentDetailExpanded: OnChangeFn<ExpandedState>;
  setEditingRowId: React.Dispatch<React.SetStateAction<string | null>>;
  shouldRenderInitialLoading: boolean;
  stateOverlayNode?: React.ReactNode;
  tableContainerClassName: string | undefined;
  uiClassNames: DataTableUiClassNames;
  virtualization: DataTableProps<TData>["virtualization"];
};
